#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd present_snappyHexMesh
cleanCase

cd ../present_innerCircle
cleanCase

cd ../
cleanCase
rm -rf 0

