#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication Allclean

m4 < system/blockMeshDict.m4 > system/blockMeshDict

runApplication blockMesh

rm -rf 0


cp -rf 0.orig 0
#------------------------------------------------------------------------------
